# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('car_brand', models.CharField(choices=[(b'Audi', b'Audi'), (b'Acura', b'Acura'), (b'BMW', b'BMW'), (b'Buick', b'Buick'), (b'Cadillac', b'Cadillac'), (b'Chevrolet', b'Chevrolet'), (b'Chrysler', b'Chrysler'), (b'Citroen', b'Citroen'), (b'Dodge', b'Dodge'), (b'Fiat', b'Fiat'), (b'Ford', b'Ford'), (b'GMC', b'GMC'), (b'Honda', b'Honda'), (b'Hyundai', b'Hyundai'), (b'Infiniti', b'Infiniti'), (b'Jaguar', b'Jaguar'), (b'Jeep', b'Jeep'), (b'Kia', b'Kia'), (b'Land Rover', b'Land Rover'), (b'Lexus', b'Lexus'), (b'Mazda', b'Mazda'), (b'Mercedes-Benz', b'Mercedes-Benz'), (b'Mitsubishi', b'Mitsubishi'), (b'Nissan', b'Nissan'), (b'Porche', b'Porche'), (b'Ram', b'Ram'), (b'Saab', b'Saab'), (b'Subaru', b'Subaru'), (b'Suzuki', b'Suzuki'), (b'Tesla', b'Tesla'), (b'Toyota', b'Toyota'), (b'Volkswagen', b'Volkswagen'), (b'Volvo', b'Volvo')], default=None, max_length=10)),
                ('car_seat', models.IntegerField()),
                ('pets_allowed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('in_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='rideshare_profile.Profile')),
            ],
        ),
    ]
