# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=b'', srid=4326),
        ),
    ]
