# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0002_routes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
    ]
