# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rideshare_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0003_auto_20160503_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=rideshare_profile.models.upload_to)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='rideshare_profile.Profile')),
            ],
        ),
    ]
