# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0003_auto_20160503_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carbrand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Acura', 'Acura'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dodge', 'Dodge'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Porche', 'Porche'), ('Ram', 'Ram'), ('Saab', 'Saab'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
        ),
    ]
