# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import rideshare_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0004_auto_20160523_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to=rideshare_profile.models.upload_to),
        ),
    ]
