# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0004_auto_20160502_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination_address_line1',
            new_name='destination_line1',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='destination_address_line2',
            new_name='destination_line2',
        ),
    ]
