# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0005_auto_20160715_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='rideshare_profile.Profile'),
        ),
    ]
