# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0005_auto_20160502_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='carseat',
            new_name='car_seat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='petsallowed',
            new_name='pets_allowed',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='carbrand',
        ),
        migrations.AddField(
            model_name='profile',
            name='car_brand',
            field=models.CharField(choices=[(b'Audi', b'Audi'), (b'Acura', b'Acura'), (b'BMW', b'BMW'), (b'Buick', b'Buick'), (b'Cadillac', b'Cadillac'), (b'Chevrolet', b'Chevrolet'), (b'Chrysler', b'Chrysler'), (b'Citroen', b'Citroen'), (b'Dodge', b'Dodge'), (b'Fiat', b'Fiat'), (b'Ford', b'Ford'), (b'GMC', b'GMC'), (b'Honda', b'Honda'), (b'Hyundai', b'Hyundai'), (b'Infiniti', b'Infiniti'), (b'Jaguar', b'Jaguar'), (b'Jeep', b'Jeep'), (b'Kia', b'Kia'), (b'Land Rover', b'Land Rover'), (b'Lexus', b'Lexus'), (b'Mazda', b'Mazda'), (b'Mercedes-Benz', b'Mercedes-Benz'), (b'Mitsubishi', b'Mitsubishi'), (b'Nissan', b'Nissan'), (b'Porche', b'Porche'), (b'Ram', b'Ram'), (b'Saab', b'Saab'), (b'Subaru', b'Subaru'), (b'Suzuki', b'Suzuki'), (b'Tesla', b'Tesla'), (b'Toyota', b'Toyota'), (b'Volkswagen', b'Volkswagen'), (b'Volvo', b'Volvo')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='address_line1',
            field=models.CharField(max_length=40, verbose_name=b'Start Address line 1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='address_line2',
            field=models.CharField(blank=True, max_length=40, verbose_name=b'Start Address line 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_line1',
            field=models.CharField(max_length=40, verbose_name=b'Destination Address line 1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_line2',
            field=models.CharField(blank=True, max_length=40, verbose_name=b'Destination Address line 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_postal_code',
            field=models.CharField(max_length=10, verbose_name=b'Destination Zip Code'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_state',
            field=models.CharField(max_length=40, verbose_name=b'Destination State'),
        ),
        migrations.AlterField(
            model_name='route',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name=b'Start Zip Code'),
        ),
        migrations.AlterField(
            model_name='route',
            name='state',
            field=models.CharField(max_length=40, verbose_name=b'Start State'),
        ),
    ]
