# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0006_auto_20160601_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='avatar',
        ),
    ]
