# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rideshare_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_profile', '0007_auto_20160701_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to=rideshare_profile.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='rideshare_profile.Profile'),
        ),
    ]
